### ISSUE TITLE
State "unofficial" more clearly in the extension

### ISSUE THREAD

**Issue by jared-hughes** [jared-hughes/DesModder#13]
It isn't currently mentioned in the webstore description until a couple blocks of text down.

Put "UNOFFICIAL" (all caps) near the top of the description and in the package metadata.

**Comment by SlimRunner** [comment]
In my opinion it's not necessary to state that the extension is unofficial as boldly as you are suggesting; in fact, I think it's fine the way it is, but I understand you might not want to direct unnecessary attention from distracted folks by stating it a bit more clearly.

My reasoning is that the name of the extension itself should suggest to the average user that it is not official. The name of it is a portmanteau of Desmos and Modder. The term modding has a fair adoption among the younger generation and tech savy people (which I'm assuming is the most likely demographic of DesModder), so I believe the it should be clear to most users that the origin of the extension is not official.
