### ISSUE TITLE
Enable hidden Desmos features

### ISSUE THREAD

**Issue by jared-hughes** [jared-hughes/DesModder#31]
This one walks a thin line. Many people are aware of clickableObjects, so that can be probably be enabled safely (as it will be via #10) 

But allowing typing hypot, argmin, etc directly? Few people are aware of it, so it could waste the Desmos team's time by potentially leading them to maintain backwards-compatibility for a few users who use the special features.

Requires graph dependencies (#58)

**Comment by FabriceNeyret** [comment]
at least the clickableObjects + advancedStyling + administerSecretFolders , for a start.
