### ISSUE TITLE
[security issue] offering JS injection in graphs

### ISSUE THREAD

**Issue by FabriceNeyret** [jared-hughes/DesModder#54]
Apparently there is a new "include" feature allowing to add JS in graphs (see https://www.desmos.com/calculator/zvn1dy2ucj ).

Adding direct access to JS in a graph is fun, but it means I can now probably creates a graph that, when you load it, will destroy all your existing graphs. So I'm not sure it's that a good idea to offer such totally open feature.
If all applications with language interpreter on top of JS spend a big care are filtering out most of JS, it's for a reason. ;-)

**Comment by FabriceNeyret** [comment]
oops, apparently I misinterpreted what was going on in this graph: this was *faking* a feature he would like.

**Comment by jared-hughes** [comment]
Right, that's using his DesmosLoader tampermonkey script.
