### ISSUE TITLE
Migrate away from submodule system

### ISSUE THREAD

**Issue by jared-hughes** [jared-hughes/DesModder#61]
Using git submodules is a little confusing and has a few downsides:

 1. The commit number in `.submodules` is not very human-readable as to what it's pointing.
 2. Installing dependencies is annoying because it consists of `npm install`, and installing submodules, then `npm install`, if necessary, in submodules.
 3. The git submodule system is not very intuitive for commits and pull requests

These problems can be avoided by not using submodules at all.

Plugins can declare a `package.json`, and then Desmodder can import them using [`npm install <git-host>:<git-user>/<repo-name>
`](https://docs.npmjs.com/cli/v7/commands/npm-install). This would make the relationship to plugins more clear.

Pull requests updating new plugins in DesModder would proceed as follows:

  - each plugin maker can do whatever to work on their plugins in separate repositories
  - when ready to update into main DesModder, they put a git tag on the repository with a bumped [semver](https://semver.org/) version.
  - The pull request to DesModder would include an updated package.json via `npm install github:username/plugin-name#semver:1.2.0`

This addresses the above issues as follows:

1. Plugin versions are specified via human-readable semver in DesModder's `package.json`
2. The install process after cloning is simplified to a single `npm install` instead of 2-3 commands.
3. It seems more intuitive to me at least. Readability of point 1 helps with that

Also, updating the main DesModder repository *only for new plugin tags* may help make the commit history cleaner.

**Comment by SlimRunner** [comment]
I'm not going to say I dislike submodules, but I did have a fair bit of problems getting them to work nicely when I was forking Desmodder. Please ping me when you close this issue so that I can update my plugin accordingly.

**Comment by jared-hughes** [comment]
It appears that npm peer dependencies are made for this: https://nodejs.org/es/blog/npm/peer-dependencies/

**Comment by jared-hughes** [comment]
I did a bit of testing with using npm modules, and it seems to have the following drawbacks:

1. Editing plugins is even *less* intuitive. You can't edit directly in `node_modules/plugin-name` (it gets overwritten and loses git info), so the best way to do it requires [npm link](https://medium.com/dailyjs/how-to-use-npm-link-7375b6219557) to be able to use git. (more commands, negating benefit 2 above)
2. Unfortunately, this messes with Typescript tooltips unless editing via symlink directly through `node_modules`, which is a pain
3. Moving the plugin directory location causes a whole mess of relative/absolute imports. Switching to [`moduleResolution: node`](https://www.typescriptlang.org/docs/handbook/module-resolution.html) would help with DesModder importing the plugin modules (which only happens once), but it wouldn't help with the more common case of importing DesModder variables from the plugin modules.

So for now, the best route of action is to stay in submodules. They are designed for embedding projects like we're doing here. NPM modules are designed for dependencies. If each plugin was a separate extension that depended on a core DesModder library, then NPM modules would be more appropriate. Alas, no.

**Comment by jared-hughes** [comment]
@SlimRunner regarding your difficulties, I think I'll improve the development instructions with commonly-used git commands for dealing with submodules, notably `git checkout --recurse-submodules`.
