### ISSUE TITLE
Toggle to hide/show hidden folders? (ElFisho functionality)

### ISSUE THREAD

**Issue by Heavenira** [jared-hughes/DesModder#63]
Just as an option to unlock the features that are included here. https://chrome.google.com/webstore/detail/custom-colors-for-desmos/clcdbeolcdigfefgbhlgghepjfkpdlgi

**Comment by jared-hughes** [comment]
Do you want the feature "Set up and use custom colors" (without using rgb/hsv function)?

Otherwise, duplicate of https://github.com/jared-hughes/DesModder/issues/10 (which I am currently working on) for the hidden folders, clickableObjects, and advancedStyling.

**Comment by jared-hughes** [comment]
Closed by https://github.com/jared-hughes/DesModder/commit/62e5a39a55b7381e6a7e33ae3bbdac97d9acd3a5
