### ISSUE TITLE
Button not appearing if calculator's language isn't English

### ISSUE THREAD

**Issue by MarksonChen** [jared-hughes/DesModder#65]
If the calculator's language is set to a language not English, the menu button and the video creator button will not appear. 
The calculator's language can be changed by adding a "?lang=zn", "?lang=fr", or "?lang=ru" at the end of the link of the graph. For example, the button will appear in [https://www.desmos.com/calculator/bfvoldc9ko?lang=zn](https://www.desmos.com/calculator/bfvoldc9ko?lang=en), but not in [https://www.desmos.com/calculator/bfvoldc9ko?lang=zn](https://www.desmos.com/calculator/bfvoldc9ko?lang=zn).

**Comment by jared-hughes** [comment]
This is a strange bug. I was able to reproduce it, and it appears to be caused by the same issue as https://github.com/jared-hughes/DesModder/issues/59. Thanks for the report!
